### ISSUE TITLE
Error when setting passwords in installer/install-arch

### ISSUE THREAD

**Issue by jburnham96** [mdaffin/arch-pkgs#11]
Running into the following error when running the script:

```
*** stack smashing detected ***: <unknown> terminated
bash: line 111: 11220 Done                             echo "$user:"password"
        line 11221 Aborted                             (core dymped) | chpasswd --root /mnt
bash: Error on line 111: chpasswd --root /mnt
```

Couldn't figure out why it was happening, did a quick google but couldn't find anything, any ideas on why this could be dying?

**Comment by kontax** [comment]
I actually think that may be an issue with chpasswd - it happened to me until I used the latest Arch iso which seemed to fix it.

**Comment by mdaffin** [comment]
Sorry for the late reply. It looks like a bug in chpasswd but I have been unable to replicate this issue locally.

What version of the ISO did you encounter this with? The last version I tried with was archlinux-2019.08.01-x86_64.iso

I did find a few reports online about it. [This one](https://github.com/clearlinux/clr-installer/issues/209) seems to suggest chrooting rather than using the `--root` option might help. [This](https://www.reddit.com/r/bash/comments/bu2q4g/scripting_password_in_automated_install_script/) also suggests that might work.

If you still have the issue try this instead:

```
echo "${Username}:${Password}" | arch-chroot /mnt chpasswd
```

**Comment by jburnham96** [comment]
Tried this with a VM using the latest image and it seemed to work fine. I was using an older version when this issue was coming up. Sorry it took me so long to get back!

**Comment by mdaffin** [comment]
No worries, glad it is working now and thanks for updating the issue.
